# Generated by Django 5.0.6 on 2026-05-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_feed_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='link',
            field=models.URLField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
