# Generated by Django 5.0.6 on 2026-05-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='special',
            field=models.BooleanField(choices=[(True, 'Có'), (False, 'Không')], default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_homepage',
            field=models.BooleanField(choices=[(True, 'Có'), (False, 'Không')], default=False),
        ),
    ]
