# Generated by Django 5.0.6 on 2026-05-13 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_article_summary_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='SubCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.subcategory'),
        ),
    ]
