# Generated by Django 5.0.6 on 2026-05-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_article_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
    ]
